apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    path: ./manifests/development
    repoURL: https://github.com/65160104/test-argo-web.git
    targetRevision: HEAD